name: sync + merge
on:
  schedule:
    - cron: '30 0-15/3 * * *'
  workflow_dispatch:
jobs:
  merge-branch:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
#       - name: sync lxk0301-jd_scripts
#         uses: repo-sync/github-sync@v2
#         if: env.PAT
#         with:
#           source_repo: "https://gitee.com/lxk0301/jd_scripts.git"
#           source_branch: "master"
#           destination_branch: "gitee"
#           github_token: ${{ secrets.PAT }}
  

      - name: git-sync gitee/lxk0301/jd_scripts.git to github with private key
        uses: wei/git-sync@v3
        with:
          source_repo: "git@gitee.com:lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_repo: "nxppru/myjdsigin"
          destination_branch: "master"
          #ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          #destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
      - name: Merge gitee to main
        uses: devmasx/merge-branch@v1.3.1	
        if: env.PAT	
        with:	
          type: now	
          from_branch: master	
          target_branch: main
          github_token: ${{ secrets.PAT }}
