name: 同步e-Scripts
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:
  merge-branch:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
        with:
          persist-credentials: false          
      - name: sync scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/849165048/Scripts.git"
          source_branch: "main"
          destination_branch: "e-Scripts"
          github_token: ${{ secrets.PAT }}
